export const aboutUsLink = 'a[href="/about"]';
export const help = 'a[href="/faqs"]';
export const news = 'a[href="/news"]';
export const newsFeatured = '[class="page--news-index"]';
export const featuredContent = 'Featured Content';
export const newsData = '[data-testid="news-data"]';
export const classContainer = '[class="container"]';
export const gridMargin = '[class="card-grid margin--l"]';
export const filterButton = '[data-testid="news-filter-button"]';
export const newsFilterWebinar = '[data-testid="news-filter-checkbox-Webinar"]';
export const allContent = "All Content";
export const slideButton = '[class="icon-burger"]';
export const slideButtonClose = '[class="button slide-in-close-button button--outline-teal"]';
export const signupPage = '[href="/user/signup/"]';

export const email = '[placeholder="Email"]';
export const password = '[placeholder="Password"]'
export const repeatPassword = '[placeholder="Repeat Password"]'
export const signupSubmit = `[type="submit"]`;
export const firstName = `[placeholder="First name"]`;
export const lastName = `[placeholder="Last name"]`;
export const dobDay = '[class="js-datepicker-day dp-day"]';
export const dobMonth = 'Month';
export const dobYear = 'Year';
export const selectric = `[class="selectric-hide-select"]`;
export const datePickerDOB = '[class="js-datepicker-day dp-day"]';
export const datePickerMonths = '[class="js-datepicker-month dp-month"]';
export const datePickerYear = `[class="js-datepicker-year dp-year"]`;
export const genderPicker = '[class="selectric-items"] [data-index="1"]';
export const gender = "-- select an option --";
export const telephoneNumber = '[placeholder="Telephone"]';
export const flat = '[placeholder="Flat"]';
export const houseNumber = '[placeholder="House Name/Number"]';
export const street = '[placeholder="street"]';
export const city = '[placeholder="City"]';
export const postCode = '[placeholder="PostCode"]';
export const submit = '[type="submit"]';
export const submitBroker = '[id="submit-broker"]';
export const checkboxLegal = '[data-testid="checkbox-legal"] [name="enableDisclaimer"]';
export const fullDOB = '[placeholder="Date of Birth"]';
export const addressLine1 = '[placeholder="Address line #1"]';
export const country = '[placeholder="Country"]';